### ISSUE TITLE
A few small questions

### ISSUE THREAD

**Issue by SaVoAMP** [hkproj/transformer-from-scratch-notes#1]
Hey,

thank you so much for providing both a video and presentation slides for everyone!

I'm currently delving deep into the workings of transformers, and your materials have been incredibly helpful to me!

At first, I thought I had understood everything by now, but as I was reading some other literature, a few minor questions popped up, and I would greatly appreciate it if you could provide some insight into them.

Here my questions:

1) Did you invent the numbers in your visualizations, or did you create a notebook for each step and then visualize the values based on the model's output? (I ask because, for the purpose of understanding, I'm trying to create some of my own visualizations and I've set up a separate notebook for that. This also brings me to my second question.)

2) I was a bit confused because in your explanation of the input embedding, you exclusively use "regular" words, but later in your overall visualizations of training or inference, not only the words are present but also the tokens `SOS` and `EOS`. Did you omit these tokens for the sake of clarity in explaining the input embedding, even though they should actually be included and, just like the regular words, receive an input ID and an embedding vector? (And this question is also related to the next one.)

3) I'm a bit confused because you use both the `SOS` and `EOS` tokens for the input, but for the output, only the `EOS` token. I've been experimenting a bit with the T5 model from Hugging Face, and there it seems to be the opposite (you have only an `EOS` token for the input, and in return, you get a `pad` token at the beginning of the output, which can presumably be interpreted as an `SOS` token here, along with an `EOS` token). Is this then dependent on the library used and essentially doesn't matter?

4) This question is related to the second question. You use 'seq = 6' as the length of the input sequence "YOUR CAT IS A LOVELY CAT". Wouldn't the actual input length be 8 after tokenization (assuming both an `SOS` and `EOS` token are needed)?

I'm really sorry that I'm asking such meticulous questions, but I'm always very precise, and these questions are driving me crazy right now in my attempt to truly understand the intricacies of the Transformers' steps in detail. 

Thank you very much once again
Sarah

**Comment by hkproj** [comment]
Hello Sarah!

Let me go through the questions one by one. Before that, let me review the terminology.

Given the following sentence: "Your cat is a lovely cat".

The tokens are the single words, if we tokenize using what is known as `WordSpace` tokenizer: `[YOUR, CAT, IS, A LOVELY, CAT]`
with a total of 6 tokens.

The `Input_ids` are the position of each token in your vocabulary: `[935, 64, 52, 5, 71, 64]`. Note that the word "cat" is mapped to the same number (64)

The embeddings are vectors of size 512, representing the meaning of the word. In our case we expect the embedding associated with the first instance of the token `64` (cat) to be the same as the last instance of the token `64` (cat).

1. All the numbers in my visualizations are made up. Especially the ones related to the embeddings and input_ids. The only thing I had paid particular attention to is to make them logically correct, that is, the embedding associated with the word "cat" in the sentence "your cat is a lovely cat" is the same for both instances of the word "cat". Also, I remember I made sure that the output of the `softmax` actually sums up to one, even if the single terms are made up.
2. I avoided using tokens (if by tokens you mean the `input_ids`) because it made it easier to follow the logic. It also made it easier to visualize the training and the inference. Remember that the Transformer model never deals with the words, but only with the token_ids and the embedding.
3. The transformer model doesn't need the `[SOS]` or `[EOS]` token to be used. In fact, these tokens are just regular words for the model and they are treated as such. What matters is how you use them (Transformer models for Computer Vision for example, don't use such tokens). Why do we use `SOS` and `EOS`? Because when we do a translation task (just like in my video), we want the model to start outputting the first token given a sentence as input. If you look the training part of the video, you will notice that the encoder input is: `[SOS] english_sentence [EOS]`, the input of the decoder is always `[SOS] italian_sentence` and the target (what we expect the model to output) is `italian_sentence [EOS]`. When we inference, we don't know the output (that's what we want the model to output). So if a model has been trained to map the `[SOS]` token (given as first token in the decoder) to the first token in the output, it will produce the first translated token. I know it's not easy to understand it with words. What I suggest is you to do a few training and inference steps, just like done in my videos, but using pen and paper and highlighting with a different color the special tokens `[SOS]` and `[EOS]` at each step.
4.  The length of the sequence actually should be much higher, not only 6 or 8. If you watch my other video on how to code a transformer model from zero, you will see that we use a fixed sequence length, generally of 64, 128, 256 or longer length. This is because the weights matrices in the transformer are always fixed in size, and we can't just shrink or enlarge them for different sentences. When the sentence is too short, we append a special token to the end of the sentence called "padding" to reach the desired fixed length.

I think if you watch my video on how to code a transformer model from scratch, in which I explain all the details of the implementation, training and inference, everything will start making sense to you. This is also my greatest suggestion for everyone who wants to break into ML: code, code, code and implement papers. That's the only way to learn. It's like when you study mathematics: you can't just memorize the integration/derivation rules and hope to pass the math test, you actually need to exercise a lot by solving many derivation and integration exercises in order for your brain to connect all the dots.

Here's a link to my video on how to code a Transformer model from scratch: https://www.youtube.com/watch?v=ISNdQcPhsts

Always glad to help
Umar

**Comment by SaVoAMP** [comment]
Thank you so much for this detailed response! I will definitely watch the video.

By the way: I just realized that the `SOS` and `EOS` tokens were not displayed in my previous text when I wrote them within those angle brackets. So, many things I wrote don't make much sense unfortunately. I'm sorry if it was confusing to you. I've corrected it now.
